FROM harbor.tasn.ir/library/docker-base-images/nginx:latest-v2

WORKDIR /var/www/
ENV GRAYLOG_SERVER="graylog.default"

COPY ./ci/nginx/config/ /etc/nginx/

RUN rm /etc/nginx/conf.d/default.conf && \
	mkdir /etc/nginx/sites-enabled/

COPY ./ci/nginx/vhosts/ /etc/nginx/sites-enabled/

COPY ./sample ./sample
COPY .env ./sample

COPY ./ci/docker/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN  chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
